#include "GameGlobals.h"

int introImg[INTRO_FRAMES] = {0};
int introFrame = 0;
bool introFinished = false;
int bg1 = 0, bg2 = 0;
int mediumBg1 = 0, mediumBg2 = 0;
int bgX = 0;
int startImg = 0;
int levelSelectImg = 0;
int pauseExitImg = 0;
int easyGameOverImg = 0, easyLevelCompleteImg = 0;
int mediumGameOverImg = 0, mediumLevelCompleteImg = 0;
bool levelSelect = false;
bool highScorePage = false;
int highScorePageNumber = 0;
const int SCORES_PER_PAGE = 10;
bool settingsPage = false;
bool creditsPage = false;
bool soundEnabled = true;
bool gameComplete = false;
bool scoreSaved = false;
bool bossDefeated = false;
int enemyImg[4] = {0};
int enemyFrame = 0;
int bulletImg = 0;
int lifeImg = 0;
int coinImg = 0;
int playerBulletImg = 0;
int mouseX = 400;
int mouseY = 200;
bool gameOver = false;
bool gameStarted = false;
bool mediumLevel = false;
bool paused = false;
int coinCount = 0;
int playerLife = 5;
int charImg[RUN_FRAMES] = {0};
int jumpImg = 0;
int hitImg[HIT_FRAMES] = {0};
int dieImg[DIE_FRAMES] = {0};
int charX = 10;
int charY = 50;
int playerW = 60;
int playerH = 80;
int idx = 0;
bool playerJump = false;
bool playerHit = false;
bool playerDead = false;
int hitFrame = 0;
int dieFrame = 0;
int hitAnimTimer = 0;
int dieAnimTimer = 0;
int bgSpeed = 5;
int score = 0;

int bossImg = 0;
int bossX = 600;
int bossY = 10;
int bossW = 100;
int bossH = 120;
int bossHP = 3;
bool bossActive = false;
int bossFireTimer = 0;

int ammo = 30;
int maxAmmo = 50;
int ammoX = 1200;
int ammoY = 80;
bool ammoActive = false;

int powerImg = 0;
int powerX = 1200;
int powerY = 100;
bool powerActive = false;
int powerType = 0;
bool shieldActive = false;
bool doubleBulletActive = false;
bool speedBoostActive = false;
int powerTimer = 0;

int combo = 0;
int comboTimer = 0;
int missionKill = 0;
int missionTarget = 10;
bool nightMode = false;

Enemy enemy[3] = {};
Bullet bullet[MAX_BULLET] = {};
LifeItem lifeItem = {};
Coin coin[MAX_COIN] = {};
PlayerBullet pBullet[MAX_PLAYER_BULLET] = {};
FlyingEnemy flyingEnemy = {};
int flyingEnemyImg[2] = {0};
int flyingEnemyFrame = 0;
FlyingBullet flyingBullet[MAX_FLYING_BULLET] = {};
Spike spike[MAX_SPIKE] = {};
int spikeImg = 0;
